# Generated by Django 2.2.12 on 2020-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
