# Generated by Django 2.2.12 on 2020-04-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
