# Generated by Django 2.2.12 on 2020-04-29 12:13

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\SHUBH\\mysites\\ecommerce_project\\media(protected)'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
