# Generated by Django 2.2.12 on 2020-04-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200429_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='free',
        ),
    ]
